/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package BinaryTree

import kotlin.test.Test
import kotlin.test.assertTrue

class BtTest {
  /*
   * This test is just to ensure that the node's structure is unchanged
   */
    @Test
    fun nodeTest() {
        // Create a node
        val node = Node("This is a test")
        assertTrue(node.yesNode == null)
        assertTrue(node.noNode == null)
        val Bt = BinaryTree(node)
        Bt.root?.yesNode = Node("This is another Test!")
        assertTrue(node.yesNode != null)
    }

  /*
   * I don't even know why I am testing these two functions
   */
    @Test
    fun genNodeAndPrintIt() {
        val node = GenerateTree(4)
        assertTrue(node?.yesNode?.noNode?.yesNode != null)
        printTree(node)
    }
}
